package com.workorder.service.dao;

import com.hummer.dao.annotation.DaoAnnotation;
import com.workorder.service.support.model.po.WorkOrderHandlerFlow;

import java.util.List;

@DaoAnnotation
public interface WorkOrderHandlerFlowMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table work_order_handler_flow
     *
     * @mbg.generated
     */
    int insert(WorkOrderHandlerFlow record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table work_order_handler_flow
     *
     * @mbg.generated
     */
    int insertSelective(WorkOrderHandlerFlow record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table work_order_handler_flow
     *
     * @mbg.generated
     */
    WorkOrderHandlerFlow selectByPrimaryKey(Integer id);

    List<WorkOrderHandlerFlow> selectByWorkOrderId(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table work_order_handler_flow
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(WorkOrderHandlerFlow record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table work_order_handler_flow
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(WorkOrderHandlerFlow record);
}