package com.workorder.service.support.model.po;

import java.io.Serializable;
import java.util.Date;

/**
 * this is %,auto generator
 * @author guo.li
 */
public class Template implements Serializable {
    private Integer id;

    private String name;

    private Date createdDatetime;

    private String code;

    private String approveUserIds;

    private Integer executeUserId;

    private Boolean isDelete;

    private String projectCode;

    public String getProjectCode() {
        return projectCode;
    }

    public void setProjectCode(String projectCode) {
        this.projectCode = projectCode;
    }

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table template
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column template.id
     *
     * @return the value of template.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column template.id
     *
     * @param id the value for template.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column template.name
     *
     * @return the value of template.name
     *
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column template.name
     *
     * @param name the value for template.name
     *
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column template.created_datetime
     *
     * @return the value of template.created_datetime
     *
     * @mbg.generated
     */
    public Date getCreatedDatetime() {
        return createdDatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column template.created_datetime
     *
     * @param createdDatetime the value for template.created_datetime
     *
     * @mbg.generated
     */
    public void setCreatedDatetime(Date createdDatetime) {
        this.createdDatetime = createdDatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column template.code
     *
     * @return the value of template.code
     *
     * @mbg.generated
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column template.code
     *
     * @param code the value for template.code
     *
     * @mbg.generated
     */
    public void setCode(String code) {
        this.code = code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column template.approve_user_ids
     *
     * @return the value of template.approve_user_ids
     *
     * @mbg.generated
     */
    public String getApproveUserIds() {
        return approveUserIds;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column template.approve_user_ids
     *
     * @param approveUserIds the value for template.approve_user_ids
     *
     * @mbg.generated
     */
    public void setApproveUserIds(String approveUserIds) {
        this.approveUserIds = approveUserIds;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column template.execute_user_id
     *
     * @return the value of template.execute_user_id
     *
     * @mbg.generated
     */
    public Integer getExecuteUserId() {
        return executeUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column template.execute_user_id
     *
     * @param executeUserId the value for template.execute_user_id
     *
     * @mbg.generated
     */
    public void setExecuteUserId(Integer executeUserId) {
        this.executeUserId = executeUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column template.is_delete
     *
     * @return the value of template.is_delete
     *
     * @mbg.generated
     */
    public Boolean getIsDelete() {
        return isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column template.is_delete
     *
     * @param isDelete the value for template.is_delete
     *
     * @mbg.generated
     */
    public void setIsDelete(Boolean isDelete) {
        this.isDelete = isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table template
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", name=").append(name);
        sb.append(", createdDatetime=").append(createdDatetime);
        sb.append(", code=").append(code);
        sb.append(", approveUserIds=").append(approveUserIds);
        sb.append(", executeUserId=").append(executeUserId);
        sb.append(", isDelete=").append(isDelete);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}