package com.workorder.service.support.model.po;

import java.io.Serializable;
import java.util.Date;

/**
 * this is %,auto generator
 * @author guo.li
 */
public class WorkOrderHandlerFlow implements Serializable {
    private Integer id;

    private Integer workOrderId;

    private Integer templateId;

    private Integer handlerUserId;
    private String handlerUser;

    private Integer status;

    private Integer actionType;

    private Date createdDatetime;

    private Date lastModifiedDatetime;

    private Boolean isDelete;

    private String memo;

    private String handlerBatchId;

    public String getHandlerUser() {
        return handlerUser;
    }

    public void setHandlerUser(String handlerUser) {
        this.handlerUser = handlerUser;
    }

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table work_order_handler_flow
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column work_order_handler_flow.id
     *
     * @return the value of work_order_handler_flow.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column work_order_handler_flow.id
     *
     * @param id the value for work_order_handler_flow.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column work_order_handler_flow.work_order_id
     *
     * @return the value of work_order_handler_flow.work_order_id
     *
     * @mbg.generated
     */
    public Integer getWorkOrderId() {
        return workOrderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column work_order_handler_flow.work_order_id
     *
     * @param workOrderId the value for work_order_handler_flow.work_order_id
     *
     * @mbg.generated
     */
    public void setWorkOrderId(Integer workOrderId) {
        this.workOrderId = workOrderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column work_order_handler_flow.template_id
     *
     * @return the value of work_order_handler_flow.template_id
     *
     * @mbg.generated
     */
    public Integer getTemplateId() {
        return templateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column work_order_handler_flow.template_id
     *
     * @param templateId the value for work_order_handler_flow.template_id
     *
     * @mbg.generated
     */
    public void setTemplateId(Integer templateId) {
        this.templateId = templateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column work_order_handler_flow.handler_user_id
     *
     * @return the value of work_order_handler_flow.handler_user_id
     *
     * @mbg.generated
     */
    public Integer getHandlerUserId() {
        return handlerUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column work_order_handler_flow.handler_user_id
     *
     * @param handlerUserId the value for work_order_handler_flow.handler_user_id
     *
     * @mbg.generated
     */
    public void setHandlerUserId(Integer handlerUserId) {
        this.handlerUserId = handlerUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column work_order_handler_flow.status
     *
     * @return the value of work_order_handler_flow.status
     *
     * @mbg.generated
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column work_order_handler_flow.status
     *
     * @param status the value for work_order_handler_flow.status
     *
     * @mbg.generated
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column work_order_handler_flow.action_type
     *
     * @return the value of work_order_handler_flow.action_type
     *
     * @mbg.generated
     */
    public Integer getActionType() {
        return actionType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column work_order_handler_flow.action_type
     *
     * @param actionType the value for work_order_handler_flow.action_type
     *
     * @mbg.generated
     */
    public void setActionType(Integer actionType) {
        this.actionType = actionType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column work_order_handler_flow.created_datetime
     *
     * @return the value of work_order_handler_flow.created_datetime
     *
     * @mbg.generated
     */
    public Date getCreatedDatetime() {
        return createdDatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column work_order_handler_flow.created_datetime
     *
     * @param createdDatetime the value for work_order_handler_flow.created_datetime
     *
     * @mbg.generated
     */
    public void setCreatedDatetime(Date createdDatetime) {
        this.createdDatetime = createdDatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column work_order_handler_flow.last_modified_datetime
     *
     * @return the value of work_order_handler_flow.last_modified_datetime
     *
     * @mbg.generated
     */
    public Date getLastModifiedDatetime() {
        return lastModifiedDatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column work_order_handler_flow.last_modified_datetime
     *
     * @param lastModifiedDatetime the value for work_order_handler_flow.last_modified_datetime
     *
     * @mbg.generated
     */
    public void setLastModifiedDatetime(Date lastModifiedDatetime) {
        this.lastModifiedDatetime = lastModifiedDatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column work_order_handler_flow.is_delete
     *
     * @return the value of work_order_handler_flow.is_delete
     *
     * @mbg.generated
     */
    public Boolean getIsDelete() {
        return isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column work_order_handler_flow.is_delete
     *
     * @param isDelete the value for work_order_handler_flow.is_delete
     *
     * @mbg.generated
     */
    public void setIsDelete(Boolean isDelete) {
        this.isDelete = isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column work_order_handler_flow.memo
     *
     * @return the value of work_order_handler_flow.memo
     *
     * @mbg.generated
     */
    public String getMemo() {
        return memo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column work_order_handler_flow.memo
     *
     * @param memo the value for work_order_handler_flow.memo
     *
     * @mbg.generated
     */
    public void setMemo(String memo) {
        this.memo = memo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column work_order_handler_flow.handler_batch_id
     *
     * @return the value of work_order_handler_flow.handler_batch_id
     *
     * @mbg.generated
     */
    public String getHandlerBatchId() {
        return handlerBatchId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column work_order_handler_flow.handler_batch_id
     *
     * @param handlerBatchId the value for work_order_handler_flow.handler_batch_id
     *
     * @mbg.generated
     */
    public void setHandlerBatchId(String handlerBatchId) {
        this.handlerBatchId = handlerBatchId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table work_order_handler_flow
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", workOrderId=").append(workOrderId);
        sb.append(", templateId=").append(templateId);
        sb.append(", handlerUserId=").append(handlerUserId);
        sb.append(", status=").append(status);
        sb.append(", actionType=").append(actionType);
        sb.append(", createdDatetime=").append(createdDatetime);
        sb.append(", lastModifiedDatetime=").append(lastModifiedDatetime);
        sb.append(", isDelete=").append(isDelete);
        sb.append(", memo=").append(memo);
        sb.append(", handlerBatchId=").append(handlerBatchId);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}